sudo: required
language: node_js
scala:
- 2.11.6
node_js:
- stable
env:
  global:
  - TERM=dumb
  - secure: qM6mZn8icbaLtpyq5qIg6FX7YfcreE29oSQqYEgXK6gtBDRMx+bhKDM4nfHKApwD1/260U0QQwdQeI7FFLbUQLIn4PZsefeQXwFLiR6Kvf2PXvEnaXQY+KrU/IPl1rkqmSva8njMp0UiO7ci7YsSP79BM5kmBp/LngHK+4YhoHkR+l1u409xkfRkcDyFQi/1VfrieUWtXf0nPpvcTXDANJIOcD8uhLEW3qv/kDEEOYwcFc5cGpI3isunhiLGQ8Djo9df0S+qQb3SF3pyFrWM2L8XhdMjs0jNkcKUl8rrWBdjxktibJCfH+t49zgxTHlIitftOOx55PSBYURSlQQ4COxaEPZHaHbA5MVtETffiY96uzmgczyx/yqYla+7Wmfn+JNG6GE0rj8Qul1rPbhh4GEen0h81MBZ0+KMHhWbTnVdI/MMpV8DuPOZ2sKCivw/SosIx5p7VX5j8Oh14/o9ju5yV0IapxKa3YtYMuH1EzSdF7tCNM0VkAmwX1HXZ1iaHQT1MHwkXUR5lZb9owJF+baWdyK3hragK2bLIG8EQJN1oZ6Y+xZnIIWg8tZjbnwrwjRsT4Du7J9KudwSWuplYUMQBh5FBiOWniHLsjE/XYZ42u/DUR1tnistOPKfBI2MJoZZ9cwBx9keSLxHsEM9lHXUoD/UCtoK8BjAOCUDKD4=
  - secure: m2hjGfuHqPNNHkK8UbVZV/38TT+if/GSNPTGqpOX7pUqMv+HWQOf6b11LfyQDXPpITNEKRFMoujNl6Rrk+uuolJdUmEwH4WvVn1gKzC5p+/UFpVJgj+g3lkyxag9fbeBMHswOtiOUj5k9D5S+wQ7PmiPk61gyzaOIGKxx4k/fVJwHFJakz2JxK3NJGK9sBpKFCkz/ny9cLexV5Zhb5MujiTXdS1Q1O9oyrydhe9RcDC7XK3FYXCOfmikV/69R+t4rbMjLQ95Kba7GJdwdpMjPEY7EHvQ4d89F16OoUAn9MoNx1URDplOWAokjavzTuoS35l5Qkh67AZ311RGVOY8FQloZheJJn4nOzeYdiHePqEhdg6xjLKdeeOIb55Pbo/cSFIRLSQ5k4zIsbJfGyjcMm9L+kdxvUzMA3AwWWuF9zXHdt/5ZyoWHQCt1AEN77LXwoxQqzbTs6U0a0W+99RkBYqP6jtFaxcYDNouAIQYBYBfK7lxETPqWB5neSD+w5GdJJ00IIH7FfunE9bmr6SNjG0CRJCeSyJtYd1RW2dWWRGY8Ch0YURBby2nhkPsPZgAhfvyJD5bSWvS5VU8VjAvWEHBXVb5pLQSQKMOQndkSLie65YR7U9M5UwqFWkbK3xdp3XfcpUgHGjfyF30n8NsI0pBffTeJnQr6fJ7XwnONvc=
  - secure: S5MP8J86cmCrmPtOjfmNRrFjCemB+3zffArm25+v1lGmktvm6Zam7nv4wt3woDizLT+X8h1ybU0F7D9rVikjfgSAWm1yhuy+A6JBRUF9YXu/mwAg+E/4Qd65l+CBPtWkbdnZR+X6rFyEcVib8ZJxaL8IBGshECOuZ5fuVYcNTYDWld56jQZF7nhQ6e61wkDKdcwT+RI5iBCWu2RJFs13gSYbHZ9Yt4cByrAMB+UDZ2e70fZbhkgOm6A0GJYwzSFaPHwAoS15b8xJHKh3XzdO81sMA6b5suFXwvmesH3epU4wl+AjQoghlMFHIoTQJMdJzGPSiAsVWE83rYBkRD/K/Iuqxd9lO13WE2ibygZhIY5woAWvDDiEMf8dwe3vIBaaRLBo6WozyqKTqeZgJpWtjAsnTJzbW/ffF941rU3Yj2ZJq9w3NdQUAfyuItVDdc1ou6yZzho+kzqOMRhHSjDO0dyLLxJ9LQSlnikLrf69qC5rrbU8QSLaa8B9GpBx5NUS7WvwwUD+nyoEN6YPdkHBa43Bde7AyhOJiR9voxQbakdYtKXo9RGk8d0Ad19PJGnzE/575aO+q4x7psy0lDIwQqh9YI6u1HnfG1KDKoXArL5ULszdTk5hKEN0+SNhRr9lBck+4YT8gJWlrx1+I64fiq7jnS7NpnP6O2T4QEATFAk=
  matrix: 
install: true
script:
- npm install
- npm install -g coveralls
- npm install -g mocha
- npm install -g nyc
- npm run test
after_success:
- npm run coveralls
notifications:
  email:
  - scottchapman@us.ibm.com
