sudo: required
language: node_js
scala:
- 2.11.6
node_js:
- stable
env:
  global:
  - TERM=dumb
  matrix:
  - secure: UeYXISrFbX8Kq1XLBGu2KnlIT2O3n4iaq1wV8pdcWbAbA+I8V2rCPYXhwQJACuCnFEwN798Cdfu7z8hw/QwsXhgT//xDZRfU+LzMTgb4N48hR33A6QBunTCfioJqr8FyiFww9Wdnv58obiF0OuREDr+YFibPnwBcBvU27r9QBoY4Iy/R2RZJVDqGEqtP8KsdgmgieGAHbMh4Ii1f4XtQfNZ9O9XDkC+dxmbbOmfnB8x95ieDnWgb4sTjSe5BDpbgl1HKHrdANt1nde4UWzQcQqleUWd2mhOvTndNVh7AiDpdnumgIMh8MyzNUQb8GmGOOmM60tybjZEXxTZjlWO9WJZU++GOlMWUJIcT7eArlmSZiMRTKBXO+dDe8xePi2zUInARBgljzFISJ3yDnlQiRr8IC5TtmmhRwYWRpSbalplMjpbxG29axp/HcgK1R+gpuFWBD2WU5DOfuZPMu3qUpcqq8ke48dTGIU8OjeLTPBGB7GgC5/hayGfW+/TNGSjIQ5UELhNJRkhzkJW9Qc93ea8M6tfDWexN4Bc0wx05V/dBwH/CC6cYftjJVnnVNvuJcF1RnBfBJwA/cQWi7SdB5ThyocuJyz4XXniaL4C6okjA2ouhV+mEH+C8YBGjYCWRbGeVfaGibeNP4YVxiPyVD2pJIC1JPLOwtwMLhT3h4Lw=
  - secure: otJuqt12H3jOPJ4831VM3CpCpjQNQJcIlx9QWPsw8skaEQ63YblDYWlbrJr8Czy7BGXH6cS0lZrUIhNq+KKO39CuXoJrZ7u3fk0F56bjGWogW2tEbh9QIMTTGigOt7/cownTajuyNR3AM5RLfVgaukzeBwNd0RPS9vpMFqpjSDxsJ3Rt/5atbXPz4Z4AkOQJ74FLR5xN3tougx3hGRDZP6ldzbdoPq0Qn24bloc6VNEz6Yk68rGXbrtFeCUQgBrHVoECic7IW0B1/rGZxrJ2Px2jxyBNez1mzc/iODYohfPvIY1XYahDXpkL+oC9wH5WItQw/VsEh3x1wUFTYChTfjIY3RnyVvJOtrcHf/dR9P6MJiimRNtSUYiC2DphrZuPC61E0oRap+C0YOHYVbO9O2w6VZGOj58Z8W+Yf9J/Y4upzbveBmKqZB/neA3OfDzLsQ6uvvxT3/wGioQ46dmiCjw8Y5nCikF0a+bFDIKHQVD0j8BYyx1QQKagUJgCFmdr/+sQ4I12smr2pXzTqYV0F+MW+riz2xdU61U4T9JVl8VGrGZN+MNKrvs3oCW8wrY0aDEDj7ThQavYFCK2ZsyWlHwozEDuFPTB7MSXSSIutbgIEe9hdQLhCB0ZUM4Nvm25Au4RSwpwkqkeR0bconF+NO2gS6dljf7WSNxTAqur9cQ=
  - secure: MPsmIYPu/NeToIZIOd1TBnJ4EMf1m7B75CdlWvZQhWpS2ibl9CsjIsMGheT81KuzntKzAzXKUZZ+onXAGjNPtKTQoRqbb/J8OZU6bcmF35o06k8SzprSpMbMP3Z/xiyLeLyYmWdKMZyQRw9f+FuQ4E3SynDpPXVRo6T4IJAwFy0B1JsgTcCQ+PhaaQCwzWESNIoQTY//bWNxOHdw/CXpFXj4qfMlm8LJhWeJX4NF8GpyLoHTCTXPK+VN4xAV8oqfE/6uRvTzR8vkqX6gcTZkOh1a288z06FWbi+D2bkYDCs8bb+00UgThUzDSgvjfXXtyOaQXegPY8jLGylHjYuwFg9YJ9ZG1JOoU0CvFmqug8fZiD7AYeVOQp+KXPpM3Tn6b9CspRq9TwY7wTQIxnGkC5/Wn/ytAgGeoh5yqBmQc3gbPDEuFx9rkAoZhRC0ad1GYesVuAmgx9jGt28sTXQxq+dLwBUxYeOFgoEAkfYRMj2aQzWgmFx5BRGqs8DJn6/JZd09AuOYgWxgzngjkiLQbL71d66grwa3/DUIJvEgSWoq3NhPuhZORJG0dWz5Fybl+4ap8fCk45vxaqmdxPaZBHhNYEJfbFqjFl2cLNSTZgz/qyuwmpmd8G7JaNOgbb5ljIHR93NHD/CcsQIcEiPGreCH83kzRa1HLpUzNvLYRhk=
install: true
script:
- npm install
- npm install -g coveralls
- npm install -g mocha
- npm install -g nyc
- npm run test
after_success:
- npm run coveralls
notifications:
  email:
  - scottchapman@us.ibm.com
